#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v27
# autospec commit: 6aaa12f
#
Name     : qt5ct
Version  : 1.5
Release  : 7
URL      : https://sourceforge.net/projects/qt5ct/files/qt5ct-1.5.tar.bz2
Source0  : https://sourceforge.net/projects/qt5ct/files/qt5ct-1.5.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: qt5ct-bin = %{version}-%{release}
Requires: qt5ct-data = %{version}-%{release}
Requires: qt5ct-lib = %{version}-%{release}
Requires: qt5ct-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : mesa-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-staticdev
BuildRequires : qttools-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
qt5ct - Qt5 Configuration Tool
This program allows users to configure Qt5 settings (theme, font, icons, etc.)
under DE/WM without Qt integration.

%package bin
Summary: bin components for the qt5ct package.
Group: Binaries
Requires: qt5ct-data = %{version}-%{release}
Requires: qt5ct-license = %{version}-%{release}

%description bin
bin components for the qt5ct package.


%package data
Summary: data components for the qt5ct package.
Group: Data

%description data
data components for the qt5ct package.


%package lib
Summary: lib components for the qt5ct package.
Group: Libraries
Requires: qt5ct-data = %{version}-%{release}
Requires: qt5ct-license = %{version}-%{release}

%description lib
lib components for the qt5ct package.


%package license
Summary: license components for the qt5ct package.
Group: Default

%description license
license components for the qt5ct package.


%prep
%setup -q -n qt5ct-1.5
cd %{_builddir}/qt5ct-1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1748671887
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1748671887
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt5ct
cp %{_builddir}/qt5ct-%{version}/COPYING %{buildroot}/usr/share/package-licenses/qt5ct/bb1748d3a8313c2bba3f5d0530634f092433753b || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qt5ct

%files data
%defattr(-,root,root,-)
/usr/share/applications/qt5ct.desktop
/usr/share/qt5ct/colors/airy.conf
/usr/share/qt5ct/colors/darker.conf
/usr/share/qt5ct/colors/dusk.conf
/usr/share/qt5ct/colors/ia_ora.conf
/usr/share/qt5ct/colors/sand.conf
/usr/share/qt5ct/colors/simple.conf
/usr/share/qt5ct/colors/waves.conf
/usr/share/qt5ct/qss/fusion-fixes.qss
/usr/share/qt5ct/qss/scrollbar-simple.qss
/usr/share/qt5ct/qss/sliders-simple.qss
/usr/share/qt5ct/qss/tooltip-simple.qss
/usr/share/qt5ct/qss/traynotification-simple.qss

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/platformthemes/libqt5ct.so
/usr/lib64/qt5/plugins/styles/libqt5ct-style.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt5ct/bb1748d3a8313c2bba3f5d0530634f092433753b
